/**
 * Service Worker Generator — Multi-Strategy Caching
 *
 * Generates a sw.js file with three caching strategies:
 * - Network-First: HTML documents (fresh content, offline fallback)
 * - Cache-First: Static assets (CSS, JS, fonts — immutable)
 * - Stale-While-Revalidate: Images (fast display, background update)
 *
 * @module generate-sw
 */

/**
 * Generate sw.js content with multi-strategy caching.
 * @param {import('../types.js').DfgrowConfig} config
 * @returns {string}
 */
export function generateServiceWorker(config) {
  const cacheVersion = `df-${config.site.domain.replace(/[^a-z0-9]/gi, '')}-${Date.now()}`;

  return `/**
 * Service Worker — Auto-generated by @gcwjkj/dfgrow-base
 * Multi-strategy caching for optimal performance
 * Cache version: ${cacheVersion}
 */

const CACHE_VERSION = '${cacheVersion}';
const CACHE_HTML = CACHE_VERSION + '-html';
const CACHE_STATIC = CACHE_VERSION + '-static';
const CACHE_IMG = CACHE_VERSION + '-img';

// ── Install: precache critical static assets ──────────────
self.addEventListener('install', (event) => {
  const precacheUrls = [
    '/',
    '/favicon.ico',
    '/manifest.json',
  ];
  event.waitUntil(
    caches.open(CACHE_STATIC).then((cache) => cache.addAll(precacheUrls).catch(() => {}))
  );
  self.skipWaiting();
});

// ── Activate: clean old caches ───────────────────────────
self.addEventListener('activate', (event) => {
  const validCaches = [CACHE_HTML, CACHE_STATIC, CACHE_IMG];
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith('df-') && !validCaches.includes(key))
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

// ── Fetch: route requests to appropriate strategy ─────────
self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only handle GET requests
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Skip cross-origin requests (analytics, CDN fonts, etc.)
  if (url.origin !== self.location.origin) return;

  // Skip non-http(s) requests
  if (!url.protocol.startsWith('http')) return;

  // Route to strategy
  if (isHTMLRequest(request, url)) {
    event.respondWith(networkFirst(request, CACHE_HTML));
  } else if (isStaticAsset(request, url)) {
    event.respondWith(cacheFirst(request, CACHE_STATIC));
  } else if (isImageRequest(request, url)) {
    event.respondWith(staleWhileRevalidate(request, CACHE_IMG));
  }
});

// ── Strategy: Network-First (HTML) ────────────────────────
// Fresh content when online, cached when offline
async function networkFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  try {
    const networkResponse = await fetch(request);
    if (networkResponse && networkResponse.ok) {
      cache.put(request, networkResponse.clone());
    }
    return networkResponse;
  } catch (err) {
    const cached = await cache.match(request);
    if (cached) return cached;
    // Offline fallback — try cached root page
    const rootCached = await cache.match('/');
    if (rootCached) return rootCached;
    throw err;
  }
}

// ── Strategy: Cache-First (CSS/JS/Fonts) ──────────────────
// Serve from cache, only fetch if not cached
async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  if (cached) return cached;
  try {
    const networkResponse = await fetch(request);
    if (networkResponse && networkResponse.ok) {
      cache.put(request, networkResponse.clone());
    }
    return networkResponse;
  } catch (err) {
    // Return empty response for missing static assets
    return new Response('', { status: 504, statusText: 'Gateway Timeout' });
  }
}

// ── Strategy: Stale-While-Revalidate (Images) ─────────────
// Show cached immediately, update in background
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const fetchPromise = fetch(request)
    .then((networkResponse) => {
      if (networkResponse && networkResponse.ok) {
        cache.put(request, networkResponse.clone());
      }
      return networkResponse;
    })
    .catch(() => cached);
  return cached || fetchPromise;
}

// ── Request type detection ───────────────────────────────
function isHTMLRequest(request, url) {
  return (
    request.mode === 'navigate' ||
    (request.headers.get('accept') || '').includes('text/html') ||
    url.pathname.endsWith('/') ||
    url.pathname.endsWith('.html')
  );
}

function isStaticAsset(request, url) {
  return (
    url.pathname.endsWith('.css') ||
    url.pathname.endsWith('.js') ||
    url.pathname.endsWith('.woff') ||
    url.pathname.endsWith('.woff2') ||
    url.pathname.endsWith('.ttf') ||
    url.pathname.endsWith('.otf') ||
    url.pathname.endsWith('.json')
  );
}

function isImageRequest(request, url) {
  return (
    (request.headers.get('accept') || '').includes('image/') ||
    url.pathname.endsWith('.webp') ||
    url.pathname.endsWith('.png') ||
    url.pathname.endsWith('.jpg') ||
    url.pathname.endsWith('.jpeg') ||
    url.pathname.endsWith('.gif') ||
    url.pathname.endsWith('.svg') ||
    url.pathname.endsWith('.avif')
  );
}
`;
}
